version: "3.9"

services:
  db:
    image: postgres:14-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  redis:
    image: redis:6.2.6-alpine
    restart: always
  rabbitmq:
    image: rabbitmq:3.9-alpine
    restart: always
    env_file:
      - .env
  control_panel:
    build: services/control_panel
    restart: always
    ports:
      - '1111:80'
    depends_on:
      - control_panel_api
    environment:
      NODE_ENV: production
    env_file:
      - .env
  worker:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m celery --app services.worker.app worker --loglevel ${LOGURU_LEVEL} --concurrency=1
    depends_on:
      - redis
      - rabbitmq
    env_file:
      - .env
    volumes:
      - cached_posts:/tmp/posts
  control_panel_api:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8000'
    depends_on:
      - db
    command: python -m uvicorn services.control_panel_api.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
  assistant_manager:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m services.assistant_manager.main
    depends_on:
      - assistant
    env_file:
      - .env
  assistant:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m services.assistant.main
    depends_on:
      - redis
      - worker
    env_file:
      - .env
    volumes:
      - cached_posts:/tmp/posts
  flower:
    image: mher/flower:0.9.7
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis
      - worker

volumes:
  db:
    driver: local
  cached_posts:
