version: "3.9"

services:
  redis:
    image: redis:6.2.6
    restart: always
    ports:
      - "6364:6379"
  rabbitmq:
    image: rabbitmq:3.9
    restart: always
    ports:
      - "5672:5672"
  worker:
    build:
      context: '.'
      dockerfile: services/worker/Dockerfile
    restart: always
    depends_on:
      - redis
#      - rabbitmq
    environment:
      BROKER_URL: "redis://redis"
      BACKEND_URL: "redis://redis"
  assistant_manager:
    build:
      context: '.'
      dockerfile: services/assistant_manager/Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      TELEGRAM_API_TOKEN: "${TELEGRAM_API_TOKEN}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
  assistant:
    build:
      context: '.'
      dockerfile: services/assistant/Dockerfile
    restart: always
    depends_on:
      - redis
      - worker
    environment:
      AIOTDLIB_API_ID: "${AIOTDLIB_API_ID}"
      AIOTDLIB_API_HASH: "${AIOTDLIB_API_HASH}"
      PHONE_NUMBER: "${PHONE_NUMBER}"
      REDIS_HOST: redis
      REDIS_PORT: 6379