version: "3.9"

services:
  worker:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m celery --app services.worker.app worker --loglevel INFO --concurrency=1
    environment:
      ASSISTANT_GRPC_ADDR: "assistant:50051"
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
      CELERY_RESULT_BACKEND: "redis://redis"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - cached_posts:/tmp/posts
  assistant_manager:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m services.assistant_manager.main
      - assistant
    environment:
      TELEGRAM_API_TOKEN: "${TELEGRAM_API_TOKEN}"
      MY_TELEGRAM_ID: "${MY_TELEGRAM_ID}"
      ASSISTANT_GRPC_ADDR: "assistant:50051"
      ASSISTANT_MANAGER_GRPC_ADDR: "assistant_manager:50052"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "50052"
  assistant:
    build:
      context: '.'
      dockerfile: Dockerfile
    restart: always
    command: python -m services.assistant.main
    depends_on:
      - worker
      - assistant_manager
    ports:
      - "50051"
    environment:
      MY_TELEGRAM_ID: "${MY_TELEGRAM_ID}"
      ASSISTANT_MANAGER_GRPC_ADDR: "assistant_manager:50052"
      ASSISTANT_GRPC_ADDR: "assistant:50051"
      AIOTDLIB_API_ID: "${AIOTDLIB_API_ID}"
      AIOTDLIB_API_HASH: "${AIOTDLIB_API_HASH}"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CELERY_BROKER_URL: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq"
      CELERY_RESULT_BACKEND: "redis://redis"
    volumes:
      - cached_posts:/tmp/posts

volumes:
  db:
    driver: local
  cached_posts:

networks:
  default:
    name: shared