version: "3.9"

services:
  db:
    ports:
      - '5555:5432'
    env_file:
      - .env.test

  redis:
    ports:
      - "6380:6379"

  rabbitmq:
    ports:
      - "5673:5672"
    env_file:
      - .env.test

  web:
    environment:
      NODE_ENV: development
    env_file:
      - .env.test
    volumes:
      - './src:/app'

  worker:
    restart: "no"
    env_file:
      - .env.test
    volumes:
      - cached_posts:/tmp/posts
      - "./src:/app"

  api:
    restart: "no"
    ports:
      - '8000:8000'
    env_file:
      - .env.test
    volumes:
      - './src:/app'

  assistant_manager:
    restart: "no"
    env_file:
      - .env.test
    ports:
      - "50052:50052"
    volumes:
      - "./src:/app"

  assistant:
    restart: "no"
    ports:
      - "50051:50051"
    env_file:
      - .env.test
    volumes:
      - cached_posts:/tmp/posts
      - "./src:/app"

  flower:
    env_file:
      - .env.test
    ports:
      - "${FLOWER_PORT}:${FLOWER_PORT}"

volumes:
  db:
    driver: local
  cached_posts:
