name: Run smoke tests

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  python-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.4.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Poetry ${{matrix.poetry-version}}
        run: pipx install poetry==${{matrix.poetry-version}}
      - name: Setup Python ${{matrix.python-version}}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
          cache: poetry
      - name: Install dependencies
        run: poetry install
      - name: Run Python smoke tests
        run: poetry run pytest -m smoke
